I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 24, in script
    show fia test at halfsize, right
  File "game/script.rpy", line 24, in <module>
    show fia test at halfsize, right
NameError: name 'halfsize' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 24, in script
    show fia test at halfsize, right
  File "C:\Users\Mike\Documents\Ren'Py\renpy\ast.py", line 1037, in execute
    show_imspec(self.imspec, atl=getattr(self, "atl", None))
  File "C:\Users\Mike\Documents\Ren'Py\renpy\ast.py", line 1000, in show_imspec
    at_list = [ renpy.python.py_eval(i) for i in at_list ]
  File "C:\Users\Mike\Documents\Ren'Py\renpy\python.py", line 1416, in py_eval
    return eval(py_compile(source, 'eval'), globals, locals)
  File "game/script.rpy", line 24, in <module>
    show fia test at halfsize, right
NameError: name 'halfsize' is not defined

Windows-7-6.1.7601-SP1
Ren'Py 6.18.3.761
HellhoundVN 0.0
